CREATE TABLE PRICES (
  PRICE_ID      INTEGER PRIMARY KEY AUTO_INCREMENT,
  BRAND_ID      INTEGER,
  START_DATE    TIMESTAMP,
  END_DATE      TIMESTAMP,
  PRICE_LIST    INTEGER,
  PRODUCT_ID    INTEGER,
  PRIORITY      INTEGER,
  PRICE         DECIMAL(10,2),
  CURR          VARCHAR(10)
);